import littledata from '@littledata/headless-shopify-sdk'
import {
	saveClientIdToMeteorSession,
	saveSessionIdToMeteorSession,
	saveShopifyNotesToMeteorSession,
} from '../buyNow/helpers'

/**
 * Function to fetch client ids generated by the trackers (GA, Segment, FB) on the headless frontend
 * @param {object} trackerIds GA3 Property id, GA4 Measurement id, Segment write key or FB pixel id, or any combination of them
 * @returns {Promise<IShopifyNoteAttribute[]>} we are using fetchClientIds method from the Littledata Headless Shopify SDK
 * to fetch client ids and then save them to the Meteor Session object
 */
export const fetchClientIds = trackerIds => {
	// we are deconstructing the trackerIds object just for demonstration purposes
	const {
		ga3PropertyId,
		ga4MeasurementId,
		fbPixelId,
		segmentWriteKey,
	} = trackerIds
	return littledata
		.fetchClientIds({
			ga3PropertyId,
			ga4MeasurementId,
			fbPixelId,
			segmentWriteKey,
		})
		.then(shopifyNoteAttributes => {
			saveClientIdToMeteorSession(shopifyNoteAttributes)
			saveSessionIdToMeteorSession(shopifyNoteAttributes)
			saveShopifyNotesToMeteorSession(shopifyNoteAttributes)
		})
}
